#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/baldur

PRODUCT_PACKAGES += lenovo_baldur_vendor_etc_dcp_symbols_dcp_elf

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_CAMERA_ICP_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_CAMERA_ICP_1_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_evass_b00

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_evass_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_evass_mdt

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_gen80000_zap_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_gen80200_zap_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_gen80900_zap_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu33_4v_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu33_4v_unsigned_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu35_4v_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu35_4v_unsigned_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu40_1v_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu40_1v_unsigned_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu40_2v_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu40_2v_unsigned_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu40_2v_v1_mbn

PRODUCT_PACKAGES += lenovo_baldur_vendor_firmware_vpu40_2v_v1_unsigned_mbn

PRODUCT_COPY_FILES += \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/IDP_UPD/IDP_UPD_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP_UPD/IDP_UPD_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_atp/ATP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_atp/ATP_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_atp/ATP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_atp/ATP_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_cdp/CDP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp/CDP_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_cdp/CDP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp/CDP_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa884x/CDP_wsa884x_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_cdp_wsa885xi2s/CDP_wsa885xi2s_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_mtp/MTP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp/MTP_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_mtp/MTP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp/MTP_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_qmp/MTP_canoe_qmp_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_mtp_wsa884x/MTP_canoe_wsa884x_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_qrd/QRD_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd/QRD_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_qrd/QRD_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd/QRD_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_acdb_cal.acdb \
    vendor/lenovo/baldur/proprietary/vendor/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/canoe_qrd_wsa884x/QRD_canoe_wsa884x_workspaceFileXml.qwsp \
    vendor/lenovo/baldur/proprietary/vendor/etc/audio/sku_canoe/mixer_paths_canoe_qrd_wsa884x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_canoe/mixer_paths_canoe_qrd_wsa884x.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/backend_conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/backend_conf.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/cablconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cablconfig.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/display/SVIConfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/SVIConfig.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/display/panel_baldur_nt36523_csot_3k_dsc_vid_C3D_cali_p3.txt:$(TARGET_COPY_OUT_VENDOR)/etc/display/panel_baldur_nt36523_csot_3k_dsc_vid_C3D_cali_p3.txt \
    vendor/lenovo/baldur/proprietary/vendor/etc/display/panel_baldur_nt36523_csot_3k_dsc_vid_C3D_cali_srgb.txt:$(TARGET_COPY_OUT_VENDOR)/etc/display/panel_baldur_nt36523_csot_3k_dsc_vid_C3D_cali_srgb.txt \
    vendor/lenovo/baldur/proprietary/vendor/etc/display/qdcm_calib_data_nt36523_3k_fhd_plus_165Hz_DPHY_video_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_nt36523_3k_fhd_plus_165Hz_DPHY_video_panel.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/display/qdcm_calib_data_nt37801_amoled_cmd_mode_dsi_csot_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_nt37801_amoled_cmd_mode_dsi_csot_panel_with_DSC.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/display/qdcm_calib_data_nt37801_amoled_cmd_mode_dsi_csot_panel_with_DSC_CPHY.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_nt37801_amoled_cmd_mode_dsi_csot_panel_with_DSC_CPHY.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/displayconfig/display_id_4630946261688083603.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630946261688083603.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/displayconfig/display_id_4630946850534658451.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630946850534658451.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/displayconfig/display_id_4630947039571902850.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947039571902850.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/displayconfig/display_id_4630947039571902851.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947039571902851.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/displayconfig/display_id_4630947075271898515.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947075271898515.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/dolby_vision.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/dolby_vision.cfg \
    vendor/lenovo/baldur/proprietary/vendor/etc/init/android.hardware.gatekeeper-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service-qti.rc \
    vendor/lenovo/baldur/proprietary/vendor/etc/init/android.hardware.gatekeeper-service-spu-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service-spu-qti.rc \
    vendor/lenovo/baldur/proprietary/vendor/etc/init/android.hardware.security.keymint-service-spu-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-spu-qti.rc \
    vendor/lenovo/baldur/proprietary/vendor/etc/init/android.hardware.weaver-service-spu-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.weaver-service-spu-qti.rc \
    vendor/lenovo/baldur/proprietary/vendor/etc/init/init.vendor.qti.hardware.spu.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.qti.hardware.spu.service.rc \
    vendor/lenovo/baldur/proprietary/vendor/etc/init/vendor.dolby.media.c2-service-vision.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2-service-vision.rc \
    vendor/lenovo/baldur/proprietary/vendor/etc/init/vendor.lenovo.hardware.touchscreen-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lenovo.hardware.touchscreen-service.rc \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_canoe_sku1/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_canoe_sku1/video_system_specs.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_canoe_sku2/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_canoe_sku2/video_system_specs.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_canoe_sku3/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_canoe_sku3/video_system_specs.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_canoe_v1/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_canoe_v1/video_system_specs.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_canoe_v2/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_canoe_v2/video_system_specs.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_canoe_sku1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_canoe_sku1.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_canoe_sku1_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_canoe_sku1_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_canoe_sku3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_canoe_sku3.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_canoe_sku3_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_canoe_sku3_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_canoe_v1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_canoe_v1.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_canoe_v2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_canoe_v2.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_canoe_v2_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_canoe_v2_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_performance_canoe_sku1_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_canoe_sku1_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_performance_canoe_sku2_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_canoe_sku2_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_performance_canoe_sku3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_canoe_sku3.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_performance_canoe_sku3_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_canoe_sku3_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_performance_canoe_v1_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_canoe_v1_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_codecs_performance_canoe_v2_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_canoe_v2_vendor.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/media_profiles_canoe_sku3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_canoe_sku3.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/modem_configs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem_configs.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/perf/qapeboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/qapeboostsconfig.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/perf/testcommonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testcommonresourceconfigs.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/perf/testtargetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/testtargetresourceconfigs.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/pwr/CameraPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/CameraPowerOptFeature.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/pwr/GamePowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/GamePowerOptFeature.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/pwr/OffScreenPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/OffScreenPowerOptFeature.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/pwr/VideoPowerOptFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwr/VideoPowerOptFeature.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/qvirtmgr-vndr.json:$(TARGET_COPY_OUT_VENDOR)/etc/qvirtmgr-vndr.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_aw963xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_aw963xx_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_aw963xx_0_sar_register.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_aw963xx_0_sar_register.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_bu52053nvx_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_fcal_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_fcal_mmc56x3x_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_icm536xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_icm536xx_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_lsm6dsv_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_mmc56x3x_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_qmc630x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_qmc630x_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/kaanapali_stk3acx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kaanapali_stk3acx_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/molokai_fcal_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/molokai_fcal_mmc56x3x_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/molokai_tmd3765_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/molokai_tmd3765_0.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/qsh_camera_common.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/qsh_camera_ov32c4c_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_ov32c4c_4.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/qsh_camera_s5kjn5_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_s5kjn5_3.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/qsh_camera_s5kjn5_3_actuator.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_s5kjn5_3_actuator.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/lenovo/baldur/proprietary/vendor/etc/sensors/javalibs/odpmanagerlib-aar:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/javalibs/odpmanagerlib-aar \
    vendor/lenovo/baldur/proprietary/vendor/etc/telephony_packages.xml:$(TARGET_COPY_OUT_VENDOR)/etc/telephony_packages.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_battery_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_0.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_battery_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_1.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_battery_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_2.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_battery_3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_3.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_common_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_common_0.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_common_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_common_1.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_cpu_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_0.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_cpu_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_1.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_cpu_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_2.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_cpu_3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_3.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal-engine_cpu_4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_4.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/thermal_user_case.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_user_case.conf \
    vendor/lenovo/baldur/proprietary/vendor/etc/wifi/sar-vendor-cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/sar-vendor-cmd.xml \
    vendor/lenovo/baldur/proprietary/vendor/etc/yellochick_v1.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/yellochick_v1.pmd \
    vendor/lenovo/baldur/proprietary/vendor/firmware/10_100_green.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/10_100_green.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/10_30_red.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/10_30_red.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/10_60_blue.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/10_60_blue.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/aw22xxx_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_fw.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_acf.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/dcp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dcp.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/lenovo/baldur/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/lenovo/baldur/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/lenovo/baldur/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/lenovo/baldur/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/lenovo/baldur/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/lenovo/baldur/proprietary/vendor/firmware/gen80000_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80000_sqe.fw \
    vendor/lenovo/baldur/proprietary/vendor/firmware/gen80200_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80200_gmu.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/gen80200_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80200_sqe.fw \
    vendor/lenovo/baldur/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/lenovo/baldur/proprietary/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/bitmlconfig.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/camxfl115indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl115indices.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/camxfl300v1indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v1indices.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/camxfl300v2indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v2indices.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/camxflcustom300indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxflcustom300indices.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/chifdnodeconfig.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/chifdnodeconfig.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.chi.featurecompatibilityspecification.netrani.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.chi.featurecompatibilityspecification.netrani.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.chi.featurecompatibilityspecification.skyros.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.chi.featurecompatibilityspecification.skyros.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.chi.featurecompatibilityspecification.sm7750.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.chi.featurecompatibilityspecification.sm7750.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.chi.featurecompatibilityspecification.sm8750.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.chi.featurecompatibilityspecification.sm8750.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.chi.featurecompatibilityspecification.sm8850.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.chi.featurecompatibilityspecification.sm8850.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.ofe.profiledb.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.ofe.profiledb.default.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.ofe.profiledb.sm8850.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.ofe.profiledb.sm8850.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.gc08a8_sunwin_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.gc08a8_sunwin_front.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_imx766_lpai_ois.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_imx766_lpai_ois.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_imx766_ois.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_imx766_ois.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_imx858.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_imx858.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_s5kjn5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_s5kjn5.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_s5kjn5_sm8845.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_s5kjn5_sm8845.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg0.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg0.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg1.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg2.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5kjns_qtech_main.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5kjns_qtech_main.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.shinetech_ov32c4c.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.shinetech_ov32c4c.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.sensormodule.sony_imx888.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.sony_imx888.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.default.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.gc08a8_sunwin_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.gc08a8_sunwin_front.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_default.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_qtech_imx766.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_qtech_imx766.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_qtech_imx858.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_qtech_imx858.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_qtech_s5kjn5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_qtech_s5kjn5.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_shinetech_ov32c.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_shinetech_ov32c.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_sony_imx888.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_sony_imx888.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_tpg.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_tpg.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.molokai_tpg2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.molokai_tpg2.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.qtech_imx766.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.qtech_imx766.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.qtech_imx858.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.qtech_imx858.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.qtech_s5kjn5.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.qtech_s5kjn5.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.s5kjns_qtech_main.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5kjns_qtech_main.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.shinetech_ov32c.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.shinetech_ov32c.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.sony_imx888.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.sony_imx888.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.tpg.art.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tpg.art.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.tpg.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tpg.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/com.qti.tuned.tpg2.canoe.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.tpg2.canoe.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/fdconfigoffline.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigoffline.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/lenovo/baldur/proprietary/vendor/lib64/camera/qfdserviceconfig.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/qfdserviceconfig.bin

PRODUCT_PACKAGES += \
    btaudio_offload_if \
    c2.dolby.client \
    c2.dolby.hevc.dec \
    c2.dolby.hevc.sec.dec \
    c2.dolby.store \
    com.qti.sensor.gc08a8_sunwin_front \
    com.qti.sensor.imx858 \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hwcfg.bps \
    com.qti.hwcfg.ife \
    com.qti.hwcfg.ipe \
    com.qti.hwcfg.mctfe \
    com.qti.hwcfg.ofe \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.evadepth \
    com.qti.node.evaitof \
    com.qti.node.evawarp \
    com.qti.node.evs \
    com.qti.node.fcv \
    com.qti.node.fd \
    com.qti.node.formatconversion \
    com.qti.node.frc \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdl \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.hdralign \
    com.qti.node.itofpreprocess \
    com.qti.node.lenovo \
    com.qti.node.mctfalign \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.mlinference \
    com.qti.node.mmfalign \
    com.qti.node.multiport \
    com.qti.node.muxer \
    com.qti.node.qsatalign \
    com.qti.node.rectification \
    com.qti.node.remosaic \
    com.qti.node.sat \
    com.qti.node.seg \
    com.qti.node.signedjpeg \
    com.qti.node.spdepth \
    com.qti.node.stich \
    com.qti.node.superportraitvideo \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmlremosaic \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afc \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbr \
    com.qti.stats.awbwrapper \
    com.qti.stats.caflogicaldriver \
    com.qti.stats.cnndriver \
    com.qti.stats.exampleaf \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.roimixer \
    com.qti.stats.roimixerlib \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libcamxdummysatsnapshotfusionwrapper \
    libcamxdummysatsoftwarefusionwrapper \
    libcamxdummysatwrapper \
    libcamxevainterface \
    libdepthmapwrapper_itof \
    com.qti.camx.chiiqutils \
    com.qti.chifeaturecompatibility \
    com.qti.chiusecaseselector \
    com.qti.custom.settings \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frc \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8850 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.metadataserializer \
    com.qti.feature2.mfsr \
    com.qti.feature2.mfsr.titan \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.raw2yuvhdr \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.rtpostproc \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.platformsettings.sm8850 \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8850 \
    com.qti.sfw.settings \
    com.qti.stats.common \
    com.qti.stats.sotr \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.sfl \
    com.qualcomm.qti.mcx.usecase.extension \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth.audio-impl-qti \
    camera.qcom.core \
    camera.qcom.sm8850 \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    libaudiocorehal.default \
    libaudiocorehal.qti \
    libspuqtigatekeeper \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    lib-imscommon \
    lib-imsdcservice \
    lib-imsdpl \
    lib-imsservice \
    lib-imsvtcore \
    lib-rtpcore \
    libCB \
    libGPMTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel_svc \
    libQSEEComAPI \
    libQshQmiIDL \
    libQshSession \
    libTUITAVMInterface \
    libTrustedUIAIDL \
    libadm \
    libadreno_app_profiles \
    libadreno_compiler_cl \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libagmmixer \
    libar-pal \
    libarcsoft_video_superportrait \
    libaudioplatformconverter.qti \
    libbitmlenginev2 \
    libbluetooth_audio_session_aidl_qti \
    libcamerabuffer \
    libcamerapoweroptfeature \
    libcamxasyncdumpmanager \
    libcamxcommonutils \
    libcamxcoreutils \
    libcamxcsl \
    libcamxcslhw \
    libcamxdumpinforecorder \
    libcamxexternalformatutils \
    libcamxfdengine \
    libcamxhexlpservicebase \
    libcamxhwlfrontend \
    libcamxhwlipedriver \
    libcamxhwnodecontext \
    libcamxhwquery \
    libcamximageformatutils \
    libcamxmetadata \
    libcamxncsdatafactory \
    libcamxods \
    libcamxofehwl \
    libcamxofeswl \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxsocketclientutil \
    libcamxsocketserverutil \
    libcamxswispiqmodule \
    libcamxswlipedriver \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcamxvppservicebase \
    libcapiv2uvvendor \
    libcdsp_default_listener \
    libcdsprpc \
    libchicore \
    libchifeature2 \
    libchinodeevautils \
    libchinodehmeutils \
    libclstc_tm \
    libcneapiclient \
    libcom.qti.chinodeutils \
    libconfigdb \
    libdev_bt \
    libdev_speaker \
    libdiag \
    libdisp-aba \
    libdisplayqos \
    libdisplayskuutils \
    libdolbydecoderprocessor \
    libdolbyeglcore \
    libdolbyottcameracontrol \
    libdolbyproxyandroid \
    libdpps \
    libdrmMinimalfsHelper \
    libdrmfs \
    libdsi_netctrl \
    libdsutils \
    libeai_fixed \
    libeai_float \
    libfastcvdsp_stub \
    libfastcvopt \
    libfeutils \
    libgsl \
    libhdr_als_adapter \
    libhdr_tm \
    libhwliqinterface2 \
    libhwlispcffdump \
    libisphwsetting \
    libkcl \
    libkernelmanager \
    libkeymasterdeviceutils \
    liblistensoundmodel2vendor \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    libloadtrusteduiapp \
    liblocdiagiface \
    libmcs \
    libmdsprpc \
    libminkdescriptor \
    libminksocket_vendor \
    libmmcamera_cac \
    libnicm_dsi \
    libnicm_internal \
    libnicm_modemproxy \
    libnicm_netlink \
    libnicm_utils \
    libnicm_vh \
    liboemcrypto \
    libpowercore \
    libqape_oem_ext \
    libqc2audio_base \
    libqc2audio_hwaudiocodec \
    libqc2vppfilter \
    libqcc_file_agent \
    libqcc_sdk \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_cvpfilter \
    libqcodec2_filterbase \
    libqcodec2_imgtxrfilter \
    libqcodec2_mockfilter \
    libqcodec2_platform \
    libqcodec2_streaminteg_filter \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqcrilNrFramework \
    libqcrilNrLogger \
    libqcrildataaidl \
    libqdi \
    libqdpr \
    libqesdk_qshsession \
    libqfdservice \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqshutils \
    libqti-perfd-client \
    libqti-qesdk-secure \
    libqtigefar \
    librpmb \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdmextension \
    libsdsprpc \
    libsensinghubapi-prop \
    libsensorcal \
    libsession_ar \
    libsession_compress \
    libsession_compress_config \
    libsession_pcm \
    libsession_pcm_config \
    libsession_voice \
    libsession_voice_config \
    libshsc \
    libsiminputgenutil \
    libsnapdragoncolor-manager \
    libsnsapi \
    libsnsdiaglog \
    libsnsutils \
    libspcom \
    libspukeymint \
    libspukeymintdeviceutils \
    libspukeymintprovision \
    libspukeymintutils \
    libssd \
    libstream_compress \
    libstream_pcm \
    libsuidlookup \
    libsv \
    libthermalclient \
    libtrustedapploader \
    libvideoml \
    libvideooptfeature \
    libvpphvx \
    libvpplibrary \
    libnsp_ipc_cdsp_skel \
    libnspextensioncopyprovider \
    libnspextensionsuperresolutionprovider \
    libsvdsp \
    libvpp_svc_skel \
    sensors.qsh \
    libquasar \
    libswdapaidl \
    vendor.qti.ImsRtpService-aidl-Impl \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.offlinecamera-service-impl \
    vendor.qti.hardware.qteeconnector-V1-ndk \
    vendor.qti.qccvndhal_aidl-V1-ndk \
    vendor.qti.qccvndhal_aidl-halimpl \
    vendor_lib_rfsa_adsp_capi_dofg_nn_so_1 \
    vendor_lib_rfsa_adsp_libmlawbpostproc_dsp_skel_so \
    c2_manifest_vendor.xml \
    vendor.qti.qccvndhal_aidl-service.xml \
    adsprpcd \
    aw882xx_cali \
    camera-preamble.json \
    cdsprpcd \
    android.hardware.gatekeeper-rust-service-qti \
    android.hardware.weaver-service-spu-qti \
    dvs-aidl-service \
    vendor.dolby.media.c2-service-vision \
    vendor.lenovo.hardware.touchscreen-service \
    vendor.qti.hardware.secureprocessor \
    vendor.qti.hardware.sensorscalibrate-service \
    vendor.qti.hardware.spu-service \
    init.qti.keymaster \
    init.qti.media \
    nicmd \
    oemowninfo \
    profile_config_service \
    qcc-vendor \
    qseecomd \
    setwlansardsi0 \
    setwlansardsi1 \
    setwlansardsi2 \
    setwlansardsi3 \
    setwlansardsi4 \
    thermal-engine-v2 \
    trusteduilistener \
    vppservice

PRODUCT_PACKAGES += \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so
